language: java

notifications:
  email: false
  slack: vamaj:Os2nOIs3WgaZyP47m6eHW86e

# version numbers
jdk:
- oraclejdk8

# Use JDK 8u45. The above line just causes the use of a minor version of Java 8.
addons:
  apt:
    packages:
    - oracle-java8-installer